require("plugins/plugins-setup")
require("core.options")
require("core.keymaps")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")

require("plugins.lspconfig")
